### ISSUE TITLE
Exposed Credentials

### ISSUE THREAD

**Issue by christiannwamba** [pmbanugo/Pusher-Auth0-ChatApp#1]
Could you hide your credentials?

**Sever**
https://github.com/pmbanugo/Pusher-Auth0-ChatApp/blob/master/src/server.js#L10-Lundefined

**Client**
https://github.com/pmbanugo/Pusher-Auth0-ChatApp/blob/master/src/public/index.js#L4-L5

**Comment by pmbanugo** [comment]
Thanks
