### ISSUE TITLE
I am attaching bug report I am getting while trying this app!

### ISSUE THREAD

**Issue by JBAhire** [pmbanugo/Pusher-Auth0-ChatApp#2]
[npm-debug.log](https://github.com/pmbanugo/Pusher-Auth0-ChatApp/files/1713375/npm-debug.log)

please look into it and tell solution. I tried everything but still not able to resolve.

**Comment by pmbanugo** [comment]
Hi, Sorry for the confusion. The steps made you try to install this package through npm. It's not an npm package so you'll get errors. I've updated the setup instructions, you can try again following the new steps

**Comment by pmbanugo** [comment]
@JBAhire closing this

**Comment by JBAhire** [comment]
@pmbanugo your solution worked for me! Thanks!
